baseURL: https://wjorden.github.io
title: Case Studies
theme: hugo-theme-m10c
paginate: 8
menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: 1
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 2
    - identifier: about
      name: About
      url: /about/
      weight: 3
    - identifier: contact
      name: Contact
      url: /contact/
   # - identifier: capstone
   #   name: Capstones
   #   url: /capstones/
   #   weight: 2
   # - identifier: sql
   #    name: SQL
   #    url: /sql/
   #    weight: 2
   # - identifier: demo
   #   name: Demos
   #   url: /demos/
   #   weight: 2
   # - indentifier: excel
   #   name: Excel
   #   url: /excel/
   #   weight: 2
params:
  author: Jorden Williams
  description: Where data becomes a story.
  menu_item_separator: ' <br> '
  social:
    - icon: github
      name: Github
      url: https://github.com/wjorden
    - icon: linkedin
      name: LinkedIn
      url: https://linkedin.com/in/wjorden
    - icon: mail
      name: Email
      url: mailto:jorden.williams.1989@gmail.com

ignoreFiles:
  ["\\.Rmd$", "\\.Rmarkdown$", "_cache$"]
  
markup:
  goldmark:
    renderer:
      unsafe: true
