baseURL: https://wjorden.github.io
title: Jorden Williams
theme: hugo-theme-m10c
paginate: 8
menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: 1
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 2
    - identifier: about
      name: About
      url: /about/
      weight: 3
params:
  author: Jorden Williams
  description: Where data becomes a story.
  menu_item_separator: ' ][ '
  social:
    - icon: github
      name: Github
      url: https://github.com/wjorden
    - icon: linkedin
      name: LinkedIn
      url: https://linkedin.com/in/wjorden
    - icon: mail
      name: Email
      url: mailto:jorden.williams.1989@gmail.com

markup:
  goldmark:
    renderer:
      unsafe: true
