# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ['1.23']
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.7
      
    - name: Set up Go '1.23'
      uses: actions/setup-go@v5
      with:
         go-version: ${{ matrix.go-version }}

    - name: Install deps
      run:
        go get github.com/a-h/templ
      
    - name: Build
      run:
        templ generate
        go build -v ./...
    
    - name: Test with Go
      run: go test -json > TestResults-${{ matrix.go-version }}.json
    
    - name: Upload Go test results
      uses: actions/upload-artifact@v4
      with:
          name: Go-results-${{ matrix.go-version }}
          path: TestResults-${{ matrix.go-version }}.json
    
    - name: Run
      run: go run -v ./...
